name: Build and publish docs
on: push
  #push:
    #branches:
    #  - master
    #paths:
    #  - 'book.toml'
    #  - 'doc/**'
    #  - '!doc/api/**.yaml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install linkcheck
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir $GITHUB_WORKSPACE/mdbook-linkcheck
          cd $GITHUB_WORKSPACE/mdbook-linkcheck
          gh release --repo Michael-F-Bryan/mdbook-linkcheck download --pattern '*x86_64-unknown-linux-gnu.zip'
          unzip *x86_64-unknown-linux-gnu.zip
          rm *x86_64-unknown-linux-gnu.zip
          echo $GITHUB_WORKSPACE/mdbook-linkcheck >> $GITHUB_PATH

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Clean
        run: mdbook clean

      - name: Build
        run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/html
